


standard:
	./__misc_tests/runMe.sh


all: standard kickstart kickstart_evreads


kickstart:
	./__misc_tests/runMe.kickstart.sh

kicstart_evreads:
	./__misc_tests/runMe.kickstart.extract_fusion_reads.sh




clean:
	rm -rf ./star_fusion_outdir
	rm -rf ./star_fusion_kickstarted_outdir
